title: M. Fedatto
#logo: /assets/img/logo.png
description: Software Development Manager<br />Enterprise Architect<br />Software Engingeer
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
